import { CategoryInfo } from "../types";

export const CATEGORIES: CategoryInfo[] = [
  {
    id: "mobiles",
    name: "Mobiles & Tablets",
    slug: "mobiles",
    iconName: "Smartphone",
    description: "Best deals on smartphones, iPhones, OnePlus, Samsung & tablets",
    keywords: [
      "iphone",
      "mobile",
      "smartphone",
      "galaxy",
      "oneplus",
      "pixel",
      "redmi",
      "realme",
      "vivo",
      "oppo",
      "iqoo",
      "poco",
      "tablet",
      "ipad",
      "5g",
      "phone",
    ],
  },
  {
    id: "laptops",
    name: "Laptops & Computers",
    slug: "laptops",
    iconName: "Laptop",
    description: "MacBooks, gaming laptops, monitors & computing accessories",
    keywords: [
      "laptop",
      "macbook",
      "thinkpad",
      "dell",
      "hp",
      "lenovo",
      "asus",
      "acer",
      "intel",
      "ryzen",
      "gpu",
      "rtx",
      "monitor",
      "keyboard",
      "mouse",
      "ssd",
      "ram",
      "desktop",
    ],
  },
  {
    id: "electronics",
    name: "Electronics & Audio",
    slug: "electronics",
    iconName: "Headphones",
    description: "Headphones, TWS earbuds, smartwatches, power banks & speakers",
    keywords: [
      "headphone",
      "earbuds",
      "earphones",
      "tws",
      "airpods",
      "boat",
      "noise",
      "sony",
      "jbl",
      "speaker",
      "soundbar",
      "smartwatch",
      "powerbank",
      "charger",
      "cable",
      "camera",
      "gimbal",
      "dslr",
    ],
  },
  {
    id: "appliances",
    name: "Home Appliances & TVs",
    slug: "appliances",
    iconName: "Tv",
    description: "Smart TVs, refrigerators, air conditioners & washing machines",
    keywords: [
      "tv",
      "television",
      "oled",
      "qled",
      "ac",
      "air conditioner",
      "refrigerator",
      "fridge",
      "washing machine",
      "microwave",
      "oven",
      "vacuum",
      "geyser",
      "cooler",
      "water purifier",
      "chimney",
    ],
  },
  {
    id: "fashion",
    name: "Fashion & Apparel",
    slug: "fashion",
    iconName: "Shirt",
    description: "Clothing, sneakers, footwear, bags & designer wear",
    keywords: [
      "shirt",
      "t-shirt",
      "tshirt",
      "jeans",
      "shoes",
      "sneakers",
      "dress",
      "kurti",
      "saree",
      "jacket",
      "hoodie",
      "footwear",
      "watch",
      "sunglasses",
      "bag",
      "backpack",
      "wallet",
      "clothing",
      "nike",
      "puma",
      "adidas",
      "zara",
      "h&m",
    ],
  },
  {
    id: "beauty",
    name: "Beauty & Personal Care",
    slug: "beauty",
    iconName: "Sparkles",
    description: "Skincare, haircare, perfumes, makeup & grooming kits",
    keywords: [
      "serum",
      "cream",
      "sunscreen",
      "shampoo",
      "perfume",
      "fragrance",
      "lipstick",
      "makeup",
      "skincare",
      "grooming",
      "trimmer",
      "shaver",
      "hair dryer",
      "loreal",
      "nykaa",
      "mamaearth",
      "minimalist",
    ],
  },
  {
    id: "home-kitchen",
    name: "Home & Kitchen",
    slug: "home-kitchen",
    iconName: "UtensilsCrossed",
    description: "Cookware, kitchen appliances, furniture & home decor",
    keywords: [
      "cookware",
      "pan",
      "cooker",
      "kettle",
      "blender",
      "mixer",
      "grinder",
      "air fryer",
      "bedsheet",
      "curtain",
      "mattress",
      "sofa",
      "chair",
      "table",
      "lamp",
      "kitchen",
      "bottle",
      "tiffin",
    ],
  },
  {
    id: "gaming",
    name: "Gaming & Consoles",
    slug: "gaming",
    iconName: "Gamepad2",
    description: "PlayStation, Xbox, Nintendo Switch, gaming gears & titles",
    keywords: [
      "ps5",
      "playstation",
      "xbox",
      "nintendo",
      "switch",
      "game",
      "controller",
      "joystick",
      "gaming chair",
      "mechanical keyboard",
      "rgb",
    ],
  },
  {
    id: "travel",
    name: "Travel & Flights",
    slug: "travel",
    iconName: "Plane",
    description: "Flight tickets, hotel bookings, holiday packages & tours",
    keywords: [
      "flight",
      "hotel",
      "ticket",
      "booking",
      "holiday",
      "resort",
      "trip",
      "klook",
      "makemytrip",
      "cleartrip",
      "travel",
      "tour",
      "visa",
    ],
  },
  {
    id: "grocery",
    name: "Grocery & Gourmet",
    slug: "grocery",
    iconName: "ShoppingBag",
    description: "Daily essentials, tea, coffee, nuts, snacks & beverages",
    keywords: [
      "grocery",
      "tea",
      "coffee",
      "nuts",
      "almonds",
      "oil",
      "rice",
      "snack",
      "biscuit",
      "chocolates",
      "dry fruits",
      "whey",
      "protein",
      "supplement",
    ],
  },
  {
    id: "accessories",
    name: "Accessories & Gadgets",
    slug: "accessories",
    iconName: "Glasses",
    description: "Cases, screen guards, straps, wallets & daily carry essentials",
    keywords: [
      "case",
      "cover",
      "strap",
      "glass",
      "screen protector",
      "stand",
      "holder",
      "tripod",
      "usb hub",
      "dongle",
      "otg",
      "gadget",
    ],
  },
  {
    id: "coupons",
    name: "Coupons & Promo Codes",
    slug: "coupons",
    iconName: "TicketPercent",
    description: "Verified coupon codes, instant cashback & promotional offers",
    keywords: ["coupon", "promo", "voucher", "code", "flat", "cashback", "offer"],
  },
];

export function inferCategoryFromText(title: string = "", description: string = ""): string {
  const text = `${title} ${description}`.toLowerCase();

  for (const cat of CATEGORIES) {
    for (const kw of cat.keywords) {
      // Word boundary match or substring check for compound terms
      const regex = new RegExp(`\\b${kw}\\b`, "i");
      if (regex.test(text)) {
        return cat.name;
      }
    }
  }

  return "Electronics";
}
