import { StoreInfo } from "../types";

export const STORES: StoreInfo[] = [
  {
    id: "amazon",
    name: "Amazon India",
    slug: "amazon",
    platform: "amazon",
    tagline: "Great Indian deals on electronics, mobiles, books & daily essentials",
    logoColor: "#FF9900",
    badgeBg: "bg-amber-500/10 border-amber-500/30 text-amber-400",
    badgeText: "Amazon",
    websiteUrl: "https://www.amazon.in",
    popularCategories: ["Mobiles & Tablets", "Electronics & Audio", "Laptops & Computers", "Appliances"],
  },
  {
    id: "flipkart",
    name: "Flipkart",
    slug: "flipkart",
    platform: "flipkart",
    tagline: "Big savings on smartphones, fashion, gadgets and home appliances",
    logoColor: "#2874F0",
    badgeBg: "bg-blue-500/10 border-blue-500/30 text-blue-400",
    badgeText: "Flipkart",
    websiteUrl: "https://www.flipkart.com",
    popularCategories: ["Mobiles & Tablets", "Fashion & Apparel", "Home Appliances & TVs"],
  },
  {
    id: "croma",
    name: "Croma Electronics",
    slug: "croma",
    platform: "croma",
    tagline: "Tata's trusted electronics store with fast delivery & extended warranty",
    logoColor: "#00E0D0",
    badgeBg: "bg-teal-500/10 border-teal-500/30 text-teal-400",
    badgeText: "Croma",
    websiteUrl: "https://www.croma.com",
    popularCategories: ["Laptops & Computers", "Home Appliances & TVs", "Electronics & Audio"],
  },
  {
    id: "reliancedigital",
    name: "Reliance Digital",
    slug: "reliancedigital",
    platform: "reliancedigital",
    tagline: "Official brand store deals with store pickup and instant discounts",
    logoColor: "#E4252A",
    badgeBg: "bg-red-500/10 border-red-500/30 text-red-400",
    badgeText: "Reliance Digital",
    websiteUrl: "https://www.reliancedigital.in",
    popularCategories: ["Mobiles & Tablets", "Home Appliances & TVs", "Laptops & Computers"],
  },
  {
    id: "myntra",
    name: "Myntra",
    slug: "myntra",
    platform: "myntra",
    tagline: "Top fashion brands, sneakers, street wear and beauty collections",
    logoColor: "#FF3F6C",
    badgeBg: "bg-pink-500/10 border-pink-500/30 text-pink-400",
    badgeText: "Myntra",
    websiteUrl: "https://www.myntra.com",
    popularCategories: ["Fashion & Apparel", "Beauty & Personal Care", "Accessories & Gadgets"],
  },
  {
    id: "ajio",
    name: "AJIO",
    slug: "ajio",
    platform: "ajio",
    tagline: "Reliance trendiest fashion, footwear and exclusive international labels",
    logoColor: "#2C4152",
    badgeBg: "bg-indigo-500/10 border-indigo-500/30 text-indigo-400",
    badgeText: "AJIO",
    websiteUrl: "https://www.ajio.com",
    popularCategories: ["Fashion & Apparel", "Accessories & Gadgets"],
  },
  {
    id: "meesho",
    name: "Meesho",
    slug: "meesho",
    platform: "meesho",
    tagline: "Unbeatable low prices on apparel, home utility, accessories & more",
    logoColor: "#F43397",
    badgeBg: "bg-fuchsia-500/10 border-fuchsia-500/30 text-fuchsia-400",
    badgeText: "Meesho",
    websiteUrl: "https://www.meesho.com",
    popularCategories: ["Fashion & Apparel", "Home & Kitchen", "Accessories & Gadgets"],
  },
  {
    id: "oppo",
    name: "Oppo Store",
    slug: "oppo",
    platform: "oppo",
    tagline: "Official store promotions with exchange bonuses and bank discounts",
    logoColor: "#1EA366",
    badgeBg: "bg-emerald-500/10 border-emerald-500/30 text-emerald-400",
    badgeText: "Oppo Store",
    websiteUrl: "https://www.oppo.com/in",
    popularCategories: ["Mobiles & Tablets", "Electronics & Audio"],
  },
  {
    id: "klook",
    name: "Klook Travel",
    slug: "klook",
    platform: "klook",
    tagline: "Attractions, city passes, theme parks and international experiences",
    logoColor: "#FF5B00",
    badgeBg: "bg-orange-500/10 border-orange-500/30 text-orange-400",
    badgeText: "Klook",
    websiteUrl: "https://www.klook.com",
    popularCategories: ["Travel & Flights"],
  },
  {
    id: "igp",
    name: "Indian Gifts Portal",
    slug: "igp",
    platform: "igp",
    tagline: "Customized gifts, hampers, cakes, flowers and celebration sets",
    logoColor: "#9333EA",
    badgeBg: "bg-purple-500/10 border-purple-500/30 text-purple-400",
    badgeText: "IGP",
    websiteUrl: "https://www.igp.com",
    popularCategories: ["Home & Kitchen", "Coupons & Promo Codes"],
  },
];

export function getStoreByPlatformOrName(platformOrName: string = ""): StoreInfo | undefined {
  const norm = platformOrName.toLowerCase().replace(/[\s-_]/g, "");
  return STORES.find(
    (s) =>
      s.platform.toLowerCase() === norm ||
      s.slug.toLowerCase() === norm ||
      s.name.toLowerCase().replace(/[\s-_]/g, "").includes(norm) ||
      norm.includes(s.slug.toLowerCase())
  );
}
